version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn install && yarn run build

workflows:
  version: 2
  build:
    jobs:
      - build