version: 2
jobs:
  build:
    ...
  deploy:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: yarn install && yarn build && git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:latest
#     steps:
#       - checkout
#       - run: yarn install && yarn run build

# workflows:
#   version: 2
#   build:
#     jobs:
#       - build